---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kraken-kubeconfig
  labels:
    app.kubernetes.io/name: "kraken-kubeconfig"
data:
  config: |
    kind: Config
    apiVersion: v1
    current-context: default
    clusters:
    - name: default
      cluster:
        insecure-skip-tls-verify: true
        server: "https://api.mycluster.local:6443"
    users:
    - name: default
      user:
        token: "___PUT_YOUR_TOKEN_HERE___"
    contexts:
    - name: default
      context:
        cluster: default
        namespace: default
        user: default
    preferences: {}
