---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kraken-config-example
  labels:
    app.kubernetes.io/name: "kraken-config-example"
data:
  config.yaml: |-
    kraken:
      distribution: openshift
      kubeconfig_path: /root/.kube/config
      exit_on_failure: False
      port: 8081
      publish_kraken_status: True
      signal_state: RUN
      litmus_version: v1.13.6
      litmus_uninstall: False
      litmus_uninstall_before_run: False
      chaos_scenarios:
        - pod_scenarios:
          - - common/default_pod_scenario.yml
    cerberus:
        cerberus_enabled: True
        cerberus_url: "http://cerberus.chaos-cerberus.svc.cluster.local:8080"
        check_applicaton_routes: True
    performance_monitoring:
        deploy_dashboards: False
        repo: "https://github.com/cloud-bulldozer/performance-dashboards.git"
        kube_burner_binary_url: "https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9.1/kube-burner-0.9.1-Linux-x86_64.tar.gz"
        capture_metrics: True
        config_path: common/default_kubeburner.yaml
        metrics_profile_path: common/default_metrics.yaml
        prometheus_url:
        prometheus_bearer_token:
        uuid:
        enable_alerts: False
        alert_profile: common/default_alerts.yaml
    tunings:
        wait_duration: 45
        iterations: 1
        daemon_mode: False
