---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: kraken-cloudprovider-creds
  labels:
    app.kubernetes.io/name: "kraken-cloudprovider-creds"
stringData:
  AWS_ACCESS_KEY_ID: AKIAXXMYKEYXXX
  AWS_DEFAULT_REGION: eu-west-3
  AWS_SECRET_ACCESS_KEY: XXXXXXXXXX_MY_SECRET_KEY_XXXXXXXXXXXXXXXX
