---
kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: kraken-scenario-example
  labels:
    app.kubernetes.io/name: "kraken-scenario-example-pipeline"
    tool: cerberus
  annotations:
    tekton.dev/displayName: Define a pipeline with a single cerberus check of an Openshift cluster
spec:
  params:
    - name: awsCredentialSecret
      type: string
      description: Name of the secret key holding the aws-credentials (mandatory but used only for aws infrastructure chaos test).
      default: kraken-aws-creds
  tasks:
  - name: kraken-scenario
    params:
      - name: awsCredentialSecret
        value: $(params.awsCredentialSecret)
    taskRef:
      kind: Task
      name: kraken-scenario
    workspaces:
      - name: kraken-kubeconfig
        workspace: kraken-kubeconfig
      - name: kraken-config
        workspace: kraken-config
      - name: kraken-common
        workspace: kraken-common
  workspaces:
  - name: kraken-kubeconfig
  - name: kraken-config
  - name: kraken-common
---
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: kraken-scenario-example-run
  labels:
    app.kubernetes.io/name: "kraken-scenario-example-pipelinerun"
    tekton.dev/pipeline: kraken-scenario-example
    tool: kraken
  annotations:
    tekton.dev/displayName: Run a pipeline with a single kraken chaos test of 2 x up to 3 pod pickup by hazard.
spec:
  params:
    - name: awsCredentialSecret
      value: "kraken-aws-creds"
  pipelineRef:
    name: kraken-scenario-example
  workspaces:
    - name: kraken-kubeconfig
      configMap:
        name: kraken-kubeconfig
    - name: kraken-config
      configMap:
        name: kraken-config-example
    - name: kraken-common
      configMap:
        name: kraken-common-example
