---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: ab-load-get-example-run
  labels:
    app.kubernetes.io/name: "ab-load-get-example-taskrun"
    tool: ab
  annotations:
    tekton.dev/displayName: Run a task with a small GET example agains't the URL
spec:
  taskRef:
    name: ab-load
  params:
    - name: url
      value: "https://startx.free.beeceptor.com/"
    - name: method
      value: GET
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: ab-load-post-example-run
  labels:
    app.kubernetes.io/name: "ab-load-post-example-taskrun"
    tool: ab
  annotations:
    tekton.dev/displayName: Run a task with a small POST example agains't the URL
spec:
  taskRef:
    name: ab-load
  params:
    - name: url
      value: "https://startx.free.beeceptor.com/"
    - name: method
      value: POST
  workspaces:
  - name: body-content
    configMap:
      name: ab-load-post-example
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: ab-load-delete-example-run
  labels:
    app.kubernetes.io/name: "ab-load-delete-example-taskrun"
    tool: ab
  annotations:
    tekton.dev/displayName: Run a task with a small DELETE example agains't the URL
spec:
  taskRef:
    name: ab-load
  params:
    - name: url
      value: "https://startx.free.beeceptor.com/"
    - name: method
      value: DELETE